In [82]:
import tensorflow as tf


def windowed_dataset(dataset: tf.data.Dataset, window_size=5, shift=1, stride=1):
    windows = dataset.window(window_size, shift=shift, stride=stride, drop_remainder=True)

    def sub_to_batch(t1, t2=None):
        t1_batches = t1.batch(window_size, drop_remainder=True)

        if t2 is not None:
            t2_batches = t2.batch(window_size, drop_remainder=True)
            return tf.data.Dataset.zip(t1_batches, t2_batches)
        else:
            return t1_batches

    windows = windows.flat_map(sub_to_batch)
    return windows





In [83]:
def custom_generator():
    for i in tf.range(10):
        yield [i,i]


dataset = tf.data.Dataset.from_generator(
    custom_generator,
    output_signature=tf.TensorSpec(shape=((2)), dtype=tf.int32)  # x 的类型和形状
    # y 的类型和形状
)
 
for x in dataset:
    print('===============')
    print(x)
    
    # for y in x:
    #     print(y)
    # print(x)


tf.Tensor([0 0], shape=(2,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([2 2], shape=(2,), dtype=int32)
tf.Tensor([3 3], shape=(2,), dtype=int32)
tf.Tensor([4 4], shape=(2,), dtype=int32)
tf.Tensor([5 5], shape=(2,), dtype=int32)
tf.Tensor([6 6], shape=(2,), dtype=int32)
tf.Tensor([7 7], shape=(2,), dtype=int32)
tf.Tensor([8 8], shape=(2,), dtype=int32)
tf.Tensor([9 9], shape=(2,), dtype=int32)


In [84]:


def windowed_dataset(dataset: tf.data.Dataset, window_size=5, shift=1, stride=1):
    windows = dataset.window(window_size, shift=shift, stride=stride, drop_remainder=True)

    def sub_to_batch(t1, t2=None):
        t1_batches = t1.batch(window_size, drop_remainder=True)

        if t2 is not None:
            t2_batches = t2.batch(window_size, drop_remainder=True)
            return tf.data.Dataset.zip(t1_batches, t2_batches)
        else:
            return t1_batches

    windows = windows.flat_map(sub_to_batch)
    return windows

dataset=windowed_dataset(dataset,5)

In [91]:
l = 0
for x in dataset.skip(5):
    l += 1
    print('--------')
    print(x)
    # for y in x:
    #     print(y.numpy())
        
print(l)

--------
tf.Tensor(
[[5 5]
 [6 6]
 [7 7]
 [8 8]
 [9 9]], shape=(5, 2), dtype=int32)
1
